{
"ABACUS" : null,
"AMBER" : null,
"ANALYSIS" : ["analysis","ANALYSIS_-_CCPN", "Analysis_(CCPN)", "Analysis_CCPN", "ccpn analysis", "CCPN_analysi", "CCPN_analysis", "CCPN-analysis",
              "ccpnmr analysis", "ccpnmr_analisis", "ccpnmr_analysis", "ccpnmr-_analysis", "CcpNmr_Analysis_2.1" ],
"ANSIG" : ["ansig", "Ansig for OpenGL", "Ansig for Windows", "ANSIG-for-OpenGL", "Ansig-for-Windows", "ANSIG3.3", "ansig4opengl"],
"AQUA" : null,
"ARIA" : ["aria", "ARIA_1.2", "ARIA_2.3" ],
"ATHNOS-CANDID" : ["atnos candid", "atnos-candid", "atnos/candid", "atnos/candid_standalone",  "atnoscandid" ],
"AURELIA" : null,
"AUREMOL" : null,
"AutoAssign" : null,
"AutoStruct" : [ "autostructure", "autpstructure" ],
"AZARA" : null,
"Burrow-Owl" : ["Burrow-Owl", "Burrow_Owl"],
"CALIBA" : ["CALIBA", "CALIBRA"],
"CARA" : ["CARA", "CARA1.5"],
"CcpNMR" : ["CCcpNMR", "CCNMR", "ccnmr", "CCPN", "CcpNMR", "CcpNMR_2.1", "CcpNMR_any", "CcpNMR_suite"],
"Chimera" : [ "ucsf_chimera", "ucsf-chimera" ],
"CING" : ["CING", "CING_any"],
"CNS" : ["CNS", "CNS FOR WATER REFINEMENT", "CNS_1.2", "CNS_1.2_PATCH_LEVEL", "CNS_using_RECOORD_scripts", "CNS1.1", "CNS1.2"],
"CNSSOLVE" : ["cnssolve", "cns_solve" ],
"CS-Rosetta" : ["cs_rosetta", "cs-rosetta", "cs-noe-rdc-rosetta", "csrosetta", "CS-NOE-RDC_Rosetta", "CS-Rosetta_toolbox" ],
"CSI" : ["CSI", "Csi_1.0"],
"CurveFit" : ["curvefit_program", "curvefit" ],
"CURVES" : ["curves_+" ],
"CYANA" : ["CYANA", "CYANA_2.0", "CYANA_2.1", "CYANA_3.0", "CYANA2.1", "Cyana3.0"],
"Delta" : ["delta", "delta_nmr" ],
"DIANA" : null,
"DISCOVER" : ["discover", "discover_molecular_modeling_system", "msi_discover", "msi discover" ],
"DYANA" : ["DYANA", "DYANA-1.5"],
"ENSEMBLE" : null,
"FELIX" : ["felix","felix (msi)", "Felix 95", "Felix 97.0", "FELIX-NMR", "FELIX2000", "Felix2000", "Felix95", "FELIX95", "Felix97"],
"FMCGUI" : null,
"formatconverter" : ["ccpn format converter", "FormatConverter" ],
"FuDA" : null,
"GARANT" : null,
"GIFA" : null,
"HADDOCK" : null,
"HYPER" : null,
"in-house written software" : ["Home written Software", "home_written", "In house perl scripts", "in-house_software", "inhouse", "inhouse2"],
"INSIGHTII" : [ "insight ii", "insight", "msi insight", "insightii" ],
"KaleidaGraph" : ["kaleidagraph", "kaleidograph for windows" ],
"Kujira": ["kujir", "kujira" ],
"MARDIGRAS" : ["MARDIGRAS", "MARDGIRAS"],
"MATLAB" : ["MATLAB", "MATLAB script", "MATLAB scripts"],
"MddNMR" : ["MDD", "MddNMR", "MDD_NMR", "MDD/MDDgui", "MDDGUI", "MDDNMR"],
"ModelFree" : [ "model-free", "ModelFree", "Modelfree_4.01"],
"Module" : null,
"Molmol" : ["Molmol", "Molmol_2K.", "Molmol_2k.2", "MOLMOL_2K.2"],
"MolProbity" : null,
"MONTE" : null,
"NDEE" : null,
"NMRCompass" : null,
"NMRDraw" : ["nmrdraw", "nmrdraw_any"],
"NMRPipe" : ["nmrpipe", "nmr pipe", "nmr-pipe", "nmrpipe_any", "nmrpipee", "nnmrpipe", "pipe", "mnrpipe", "nmr_pipe", "NMRPIPE 2004-04-12", "nmrrpipe" ],
"NMRspy" : ["nmrspy"],
"NMRView" : [ "mrview", "nmrview", "nmr view", "nmr-view", "nmnrview", "NMRVIEW2.1", "NMRView5" ],
"NMRViewJ" : null,
"Olivia" : null,
"Omega Spectrometer Operating Software" : ["omega", "omega_spectrometer_operating_software" ],
"OPALp" : ["Opalp", "OPALp", "OPALp", "OPALP"],
"P-ROI" : ["p-roi system" ],
"PACES" : null,
"PALES" : null,
"PARADYANA" : null,
"PASTA" : null,
"PDBStat" : null,
"PINE" : [ "pine_server" ],
"PIPP" : ["nmrpipp", "pipp", "pipp suite" ],
"PIPP/STAPP" : ["pipp_stapp", "pipp-stapp", "pipp/stapp"],
"Procheck" : null,
"ProcheckNMR" : [ "procheck- nmr", "procheck-nmr", "prochecknmr", "prochek-nmr" ],
"PRONTO" : null,
"PRONTO3D" : ["pronto3d"],
"PROSA" : null,
"Protein Constructor" : ["protein_constructor" ],
"PyMol" : null,
"REDCAT" : null,
"REGINE" : null,
"Relax" : ["relax", "relaxfit" ],
"RNMR" : null,
"RNMRTK" : ["Rowland NMR Toolkit", "roland_nmr_toolkit", "rowland_nmr_toolkit", "rowland_nmr_toolkit_script_generator" ],
"RPF" : ["RPF(AutoStructure)", "rpf"],
"SIGMAPLOT" : ["sigmaplot"],
"Smartnotebook" : null,
"software" : ["software", "software_1", "software_2", "software_3", "software.name"],
"SPARKY" : ["sparky", "ucsf sparky", "sparky 3", "sparky_3" ],
"SPARTA" : null,
"SPSCAN" : null,
"SYBYL" : ["sybyl", "sybyl triad", "sybyl_triad", "triad", "triad (sybyl)"],
"TALOS" : ["talos", "talos_any"],
"TALOS+" : ["talo+", "talos_plus", "talosplus", "TALOSPLUS_3.60F1", "Talosplus_any", "talos+"],
"Tensor" : null,
"Tensor2" : null,
"TOPSPIN" : ["topspin", "topspin+", "Topspin_2.1", "Topspin2.1"],
"UNIO" : ["unio_10", "unio'08", "unio08", "unio10", "unio'10" ],
"unknown" : ["null_given", "not_given"],
"UXNMR" : [ "uxnmr", "uxwinnmr" ],
"VNMR" : ["varian", "varian software (vnmr)", "varian vnmr", "varian_vnmr", "vnmr", "VNMR_6.1B", "VNMR_6.1C", "VNMR6.1B", "VNMR6.1C" ],
"WhatIF" : [ "what if" ],
"X-PLOR" : ["x_plor", "x-plor", "xplor" ],
"X-PLOR NIH" : ["x-plor nih-2.9.4a", "x-plor_2.9.4a", "x-plor_nih", "x-plor-nih", "nih-xplor", "xplor-nih", "xplornih", "X-PLOR_NIH_2.16"],
"XEASY" : null,
"XEASY/CYANA" : ["XEASY,_CYANA", "XEASY,CYANA"],
"xwinnmr" : ["bruker", "bruker xwinnmr", "xwinnmr", "xwinnmr (bruker)", "XWINNMR, MacNMR, NTNMR" ],
"YASARA" : null
}
