{
"Delta NMR": "JEOL",
"AutoLink": "",
"UNIO": "Herrmann and Wuthrich",
"ASCAN": "",
"YASARA_Energy_Minimization_Server": "Yasara Biosciences",
"TALOS+": "Shen, Delaglio, Cornilescu and Bax",
"NOAH": "",
"Rosetta": "Baker et al.",
"ADAPT-NMR": "Lee, Hu, Tonelli, Bahrami, Neuhardt, Glass and Markley",
"XWIN-NMR": "Bruker Biospin",
"X-PLOR": "Brunger",
"MICS": "Shen and Bax",
"NMRSwarm": "Pickford",
"Rownald_NMR_Toolkit": "",
"AUTODOCK": "Olson",
"CS-Rosetta": "Shen, Vernon, Baker and Bax",
"HIFI": "Eghbalnia, Bahrami, Tonelli, Hallenga and Markley",
"CANDID": "Herrmann, Guntert and Wuthrich",
"XWIN NMR": "Bruker Biospin",
"RPF": "Huang, Rosato, Singh and Montelione",
"VNMRJ": "Varian",
"xwinnmr/TOPSPIN": "Bruker Biospin",
"UNIO-MATCH": "Volk, Herrmann, Wuthrich",
"Molmol": "",
"ATSAS": "",
"AMBER": "Case, Darden, Cheatham, III, Simmerling, Wang, Duke, Luo, ... and Kollman",
"RECOORD": "Nederveen et al",
"PyRPF": "CCPN",
"SCRUB": "Coggins and Zhou",
"ACME": "Delaglio, Wu and Bax",
"INCA": "",
"RIBBONS": "Carson",
"MEMBRANE_CS_ROSETTA-ARIA_2-2U3-CNS": "",
"ARIA": "Linge, O'Donoghue and Nilges",
"GAPRO": "Hiller, Fiorito, Wuthrich and Wider",
"geNMR": "",
"NMRCompass": "MSI",
"REDCAT": "Valafar and Prestegard",
"Analysis-CCPN": "CCPN",
"SANE": "Duggan, Legge, Dyson and Wright",
"Omega Spectrometer Operating Software": "General Electric",
"NMRCLUST": "Kelley",
"Olivia": "Masashi",
"xwinnmr": "Bruker Biospin",
"FANTASIA": "Banci",
"FANMEM": "Nolde, Arseniev, Vergoten, Efremov",
"in-house written software": "",
"CcpNnmr_Analysis": "CCPN",
"MestRe-C": "",
"NESSY": "",
"PASA": "",
"MAPPER": "",
"FMCGUI": "Lemak and Arrowsmith",
"TALOSN": "Shen and Bax",
"PDBStat": "Tejero, Snyder, Mao, Aramini and Montelione",
"NMRPipe(ACME)": "",
"ARIA1.1": "Linge, O'Donoghue and Nilges",
"NMRPy": "",
"nmrView_any": "Johnson, One Moon Scientific",
"AURELIA": "Neidig, Geyer, Gorler, Antz, Saffrich, Beneicke, Kalbitzer",
"X-WINNMR": "Bruker Biospin",
"RNMRTK": "",
"qMDD": "Mayzel and Orekhov",
"QUEEN": "Nabuurs, Spronk, Krieger, Maassen, Vriend and Vuister",
"HADDOCK1.3": "Bonvin",
"XEASY/CYANA": "",
"GARANT": "Bartels, Guntert, Billeter and Wuthrich",
"AutoAssign": "Zimmerman, Moseley, Kulikowski and Montelione",
"MONTE": "Hitchens, Lukin, Zhan, McCallum and Rule",
"NOEID": "Parsons",
"INSIGHTII": "Accelrys Software Inc.",
"DIANA": "Guntert, Braun and Wuthrich",
"CING": "Doreleijers, da Silva, Krieger, Nabuurs, Spronk, Stevens, Vranken, Vriend, and Vuister",
"xcrvfit": "Boyko and Sykes",
"nmrPipe/draw": "",
"QUASI": "UMR7104",
"NEASY/CARA": "",
"Burrow-Owl": "Benison",
"CNS/SCULPTOR": "",
"CYANA_3.0_intel": "Guntert, Mumenthaler and Wuthrich",
"DSSP": "",
"GROMACS_CPMD": "",
"AutoStruct": "Huang, Tejero, Powers and Montelione",
"ARIA2": "Linge, O'Donoghue and Nilges",
"UNIO-ATNOS-CANDID": "Herrmann, Guntert, Wuthrich",
"SPSCAN": "Glaser",
"OPALp": "Koradi, Billeter and Guntert",
"CRYSOL": "",
"TOTAL": "",
"CNS_1.1,_X-PLOR": "",
"NMRPipe": "Delaglio, Grzesiek, Vuister, Zhu, Pfeifer and Bax",
"Reconstruction_4D": "Stanek and Kozminski",
"CcpNmr_Entry_Completion_Interface": "CCPN",
"TALOS": "Cornilescu, Delaglio and Bax",
"MCCL": "",
"X-PLOR NIH": "Schwieters, Kuszewski, Tjandra and Clore",
"DISCOVER": "Accelrys Software Inc.",
"Foldit": "Baker et al.",
"YASARA": "Yasara Biosciences",
"CS23D": "Wishart, Arndt, Berjanskii, Tang, Zhou and Lin",
"HADDOCK_webserver": "Bonvin",
"CINDY": "Padilla",
"Mars": "Jung and Zweckstetter",
"Monte_Carlo_script": "",
"OriginPro": "",
"Checkshift": "",
"Name": "New Author Name",
"AZARA": "Boucher",
"GRAMM-X_Protein-Protein_Docking_Web_Server": "",
"NMRPipe,_SPARKY": "",
"Scrub": "Coggins and Zhou",
"GENPROC": "Mobli",
"MARDIGRAS": "Borgias, Thomas, Liu and Kumar",
"PROFIT": "Martin",
"UNIO-ATNOS-ASCAN": "Herrmann, Guntert, Wuthrich",
"NMRDraw,_CCP-NMR": "",
"Unio10'": "Herrmann and Wuthrich",
"NUChemiCS": "",
"GENXPK": "",
"ASDP": "",
"AngleSearch": "",
"AutoDep": "PDBe",
"MFT": "",
"PACES": "Coggins and Zhou",
"MODELLER": "",
"TANSY": "Isaksson, Mayzel, Saline, Pedersen, Rosenlow, Brutscher, Karlsson and Orekhov",
"What_check": "Vriend",
"CamShift": "Kohlhoff, Robustelli, Cavalli, Salvatella and Vendruscolo",
"FAWN": "Lemak and Arrowsmith",
"nmr_structure_tools": "",
"TALOS-N": "Shen and Bax",
"CSI": "Wishart, Willard, Jellard and Sykes",
"Platon": "Labudde and Leitner",
"Bruker_topsin": "Bruker Biospin",
"j-UNIO": "Herrmann and Wuthrich",
"NMRViewJ": "Johnson, One Moon Scientific",
"AMPAC": "",
"CAPP": "Garrett",
"BATCH": "",
"Pence": "Wishart and Sykes",
"CYANA": "Guntert, Mumenthaler and Wuthrich",
"CNX": "",
"FuDA": "Hansen",
"MIDAS": "",
"S3EPY": "Novak",
"ShiftCalc": "Williamson and Refaee",
"DISCO": "Martin, Yan, Bailey-Kellogg, Zhou, and Donald",
"ATNOS": "",
"SIMPSON": "",
"NMRView": "Johnson, One Moon Scientific",
"iNMR": "",
"HYPER": "",
"iCing": "Doreleijers, da Silva, Krieger, Nabuurs, Spronk, Stevens, Vranken, Vriend, and Vuister",
"Protein Constructor": "",
"PRONTO3D": "Kjur, Andersen and Poulsen",
"PROSAII": "Guntert",
"GENMAC": "",
"PSVS": "Bhattacharya and Montelione",
"Smart_Notebook": "Slupsky, Boyko, Booth and Sykes",
"CYANA_TINKER": "",
"MODULE2": "",
"AVS": "Moseley and Montelione",
"cns_2": "",
"NMRPipe_and_SPARKY": "",
"MESTRENOVA": "",
"AMIX": "",
"fastModelFree": "Loria",
"Smartnotebook": "Slupsky, Boyko, Booth and Sykes",
"SPDB": "Guex and Peitsch",
"Microcal_Origin": "",
"PROSA": "Guntert",
"OPAL": "Luginbuhl, Guntert, Billeter and Wuthrich",
"software": ".",
"MolProbity": "Chen, Arendall, Headd, Keedy, Immormino, Kapral, Murray, Richardson JS, Richardson DC",
"spinsight": "Varian",
"Tensor": "Dosset, Marion, Blackledge",
"CNSSOLVE": "",
"MUNIN": "Orekhov, Ibraghimov, Billeter",
"SPARKY_NMR_view_PIPP": "",
"cns-1.3": "",
"EXCEL": "Microsoft",
"CALIBA": "",
"ATHNOS-CANDID": "",
"SPARKY_and_NMRpipe": "",
"Smartbotebook": "Slupsky, Boyko, Booth and Sykes",
"YASARA2": "Yasara Biosciences",
"GRASP": "",
"ABACUS": "Grishaev, Steren, Wu, Pineda-Lucena and Arrowsmith",
"RASTER3D": "Merritt and Bacon",
"FANTOM": "Braun",
"SPARKY": "Goddard",
"SPARTA+": "Shen and Bax",
"PIPP": "Garrett",
"PREDITOR": "Berjanskii, Neal and Wishart",
"Relax": "d'Auvergne and Gooley",
"RCI": "Berjanskii and Wishart",
"unknown": "",
"FELIX": "Accelrys Software Inc.",
"MagRO": "Kobayashi",
"ACDHNMR_Predictor": "",
"NMRPipe/NMRDraw": "",
"GIFA": "Delsuc",
"Minuit": "",
"MATLAB": "The MathWorks Inc.",
"MCASSIGN2": "",
"Delta": "JEOL",
"CNS-ARIA": "",
"PECAN": "Eghbalnia, Wang, Bahrami, Assadi and Markley",
"TOPSPIN": "Bruker BioSpin",
"WhatCheck": "Vriend",
"formatconverter": "",
"NDEE": "",
"Kujira": "Kobayashi",
"ARIA1.2_CNS": "Linge, O'Donoghue and Nilges",
"CATIA": "",
"GROMACS": "Spoel et al.",
"HEME_METHYL_SHIFT_PATTERNS": "",
"ModelFree": "Palmer III",
"CURVES": "Lavery and Sklenar",
"VNMR": "Varian",
"TINKER": "Ponder",
"UXNMR": "Bruker Biospin",
"VnmrJ": "Varian",
"SIGMAPLOT": "",
"MddNMR": "Orekhov, Jaravine and Kazimierczuk",
"KaleidaGraph": "Synergy Software",
"CARA": "Keller and Wuthrich",
"FMC": "Lemak, Steren, Llinas and Arrowsmith",
"MATCH": "",
"Mulder": "Padrta and Sklenar",
"AUREMOL": "",
"In_house_product_plane_algorithm": "",
"LIGPLOT": "",
"CORMA": "James",
"NAMD": "",
"UBNMR": "Shen",
"jUNIO": "Herrmann and Wuthrich",
"SSA_software_package": "Stanek, Kosinski, Kozminski",
"ARIA_CNS": "Linge, O'Donoghue and Nilges",
"QME": "O'Donovan and Laue",
"VMD": "Humphrey, Dalke and Schulten",
"Procheck": "Laskowski, MacArthur, Smith, Jones, Hutchinson, Morris, Moss and Thornton",
"QSiteFinder": "Laurie and Jackson",
"ANALYSIS": "CCPN",
"PRONTO": "Kjur, Andersen and Poulsen",
"Fillshifts": "Willard, Gagne, and Mercier",
"Chimera": "Pettersen, Goddard, Huang, Couch, Greenblatt, Meng, and Ferrin",
"CcpNMR": "CCPN",
"SCULPTOR": "Charavay, Eynard, Hus, Bouvignies and Blackledge",
"Peakpick/PPFLX": "",
"NMRest": "Polshakov",
"ENSEMBLE": "Marsh, Choy, Forman-Kay",
"jeval": "",
"ORIGIN": "",
"relaxGUI": "",
"iCING": "Doreleijers, da Silva, Krieger, Nabuurs, Spronk, Stevens, Vranken, Vriend, and Vuister",
"GROMOS": "van Gunsteren and Berendsen",
"almost": "",
"DIAMOD": "Werner Braun group",
"Xwin-nmr": "Bruker Biospin",
"Mathematica": "Wolfram Research",
"X-WIN-NMR": "Bruker Biospin",
"PASD_algorithm": "",
"Aria-CNS": "Linge, O'Donoghue and Nilges",
"Custom": "",
"DeepView-Swiss_-PDBViewer": "Guex, Peitsch, Schwede, and Diemand",
"HADDOCK": "Bonvin",
"NMRi": "New Methods Research Inc.",
"vnmrj": "Varian",
"Module": "",
"NMR-SPIRIT": "",
"DYANA": "Guntert, Braun and Wuthrich",
"PINE": "Bahrami, Markley, Assadi, and Eghbalnia",
"CCP4": "",
"FTNMR": "",
"Rosetta_3": "Baker et al.",
"HYDRO": "",
"NMR-STAR": "BMRB",
"TSAR": "Kozminski, Zawadzka, Kazimiurcuk",
"PASTA": "",
"PARADYANA": "Turner et al.",
"NMNMRView": "",
"Python": "Python Software Foundation",
"Chiron": "",
"AS-DP": "",
"Magro": "Kobayashi",
"PyMol": "DeLano Scientific LLC.",
"relxn2.2": "",
"MC-SYM": "",
"FRODO": "",
"CHRMM": "",
"NACCESS": "",
"NMRDraw": "Delaglio, Grzesiek, Vuister, Zhu, Pfeifer and Bax",
"COMPASS": "Niklasson, Ahlner, Andresen, Marsh and Lundstrom",
"DASHA": "Arseniev",
"SYBYL": "Tripos",
"CYANA_3.0_OPALP": "Guntert, Mumenthaler and Wuthrich",
"ANSIG": "Kraulis",
"CNS_HADDOCK": "",
"XEASY": "Bartels et al.",
"CCPN formatConverter": "CCPN",
"PR": "Karra and Arrowsmith",
"MARS": "Jung and Zweckstetter",
"WhatIF": "Vriend",
"CNS": "Brunger, Adams, Clore, Gros, Nilges and Read",
"CurveFit": "Palmer III",
"LSQKAB": "CCP4",
"Paste-Papst": "Labudde and Leitner",
"Protein Pack": "Varian",
"ARIA2.3": "Linge, O'Donoghue and Nilges",
"ARIA2.0": "Linge, O'Donoghue and Nilges",
"PISTACHIO": "Eghbalnia, Bahrami, Wang, Assadi and Markley",
"CPMD": "",
"MestReNova": "",
"CCPNAnalysis": "CCPN",
"CHARMM": "",
"NMRspy": "Yang and Zheng",
"PROMOTIF": "Hutchinson and Thornton",
"NUCFIT": "",
"ProcheckNMR": "Laskowski and MacArthur",
"MOLSCRIPT": "Kraulis",
"NMRPIPE_and_NMRVIEW": "",
"CcpNmr_Entry_completion_Interface": "CCPN",
"SIDER": "Hansen",
"DANGLE": "Cheung, Maguire, Stevens and Broadhurst",
"AQUA": "Rullmann, Doreleijers and Kaptein",
"MAGRO": "Kobayashi",
"ARIA-CNS": "Linge, O'Donoghue and Nilges",
"SPARTA": "Shen and Bax",
"Spinsight": "Varian",
"STAPP": "Garrett",
"PALES": "Zweckstetter and Bax",
"na": "",
"XEASY/CARA": "",
"MOLMOL_NMRDRAW": "",
"Tensor2": "Dosset, Marion, Blackledge",
"Spinevolution": "Veshtort and Griffin",
"SPARKY_NMR_view_PIPP_NMRPIPE": ""
}
