{
"processing" : ["1D/2D data processing", "3D data processing","data prcessing", "data process","Data process",
            "data processing", "Data processing", "Data processing.", "Data Processing", "DATA PROCESSING", "data processing display",
            "data processing", "data processing", "NMR data procesing", "nmr data processing", "NMR data processing", "NMR data Processing",
            "NMR processing", "PDB processing", "primary data processing", "procesing", "process", "process data", "processed data",
            "processed NMR data", "Process fids.", "processing", "Processing", "PROCESSING", "Processing 3D NOESY and TOCSY and 2D HSQC",
            "processing all data", "processing data", "processing display", "processing heteronuclear NMR spectra",
            "processing (multidimensional decomposition)", "processing: NMR_Pipe", "Processing NMR spectra", "Processing of 2D & 3D data",
            "processing of data", "processing of NMR data", "Processing of NMR data", "processing of NMR spectra", "Processing of NMR spectra",
            "Processing of NMR spectra", "processing of non-uniformly sampled data", "processing of Projection-Reconstruction spectra",
            "processing of spectra", "Processing of spectra", "Processing of Spectra", "processing of the NMR raw data",
            "Processing of the specta", "processing", "Processing raw data", "processing raw NMR data", "processing spectra",
            "Processing Spectra", "Processing time domain data", "In-house developed user macros for data processing.",
            "processing (v2.1)", "processing varian format data", "process NMR data", "process NMR spectra",
            "process raw NMR spectral data from spectrometers", "process the Raw NMR data", "raw data processing",
            "raw spectral data (FID) transformations", "raw spectral data proccesing", "raw spectral data processing",
            "Raw spectral data processing", "raw spectral data transformations", "specta processing", "spectral data processing",
            "Spectral data processing", "spectral process", "spectral processing", "Spectral processing", "Spectral Processing",
            "spectra processing", "spectra Processing", "Spectra processing", "spectrum processing", "Spectrum processing",
            "Spectrum Processing", "spectrum transformation", "transform", "transform and plot; data tables", "transformation",
            "ransform/process data", "used for all data processing", "used for all FT of data"
        ],
"collection" : ["Acquire NMR data.", "acquiring", "acquisition", "Acquisition", "Acquisition of NMR experiments",
            "acquisition of NMR spectra", "acquisition of spectra", "acquisiton", "acqusition", "collection", "Collection",
            "COLLECTION", "collection of data", "collection of distance restraints", "collection (v1.3)", "constraint collection",
            "aquisition", "Aquisition of Data", "data acquisition", "Data acquisition", "Data Acquisition", "data acquisitions",
            "data acqusition", "data aquisition", "Data aquisition from the NMR", "Data aquisition on from the NMR",
            "data collection", "Data collection", "Data Collection", "DATA COLLECTION", "NMR data acquisition", "NMR data acquisitiuon",
            "NMR data acqusition", "nmr data collection", "NMR data collection", "NMR_data_collection", "NMR spectra acquisition",
            "spectra acquisition", "spectra collecting", "Spectra collection", "spectrometer operation", "spectrum acquisition",
            "Spectrum acquisition"
        ],
"data analysis" : ["2D spectra analysis", "3D data analysis", "4D data analysis", "analyses", "analysing data", "analysing NMR spectra",
            "analysis", "Analysis", "analysis 1H, 13C, and 15N chemical shifts", "analysis 3D heteronuclear spectra", "analysis and assignment",
            "analysis and display of molecule", "Analysis and display of molecules", "analysis and intergation of NMR spectra", "analysis & assignment",
            "analysis NMR data", "Analysis NMR spectra", "analysis of 15N relaxation data", "analysis of 2D and 3D NMR data",
            "analysis of 3D heteronuclear spectra", "analysis of NMR datasets", "analysis of NMR restraints violations", "Analysis of NMR spectra",
            "analysis of processed spectra", "analysis of relaxation data", "analysis of resonance assignment", "analysis of signal assignmnent",
            "analysis of spectra", "Analysis of spectra", "Analysis of stereochemical quality", "analysis of structure",
            "analysis of the NMR restraints violations", "Analysis of the spectra to obtain", "Analysis (Peak Picking)", "analyze data",
            "analyze NMR data", "analyzing", "analyzing frequency domain data", "Analyzing Main Chain assignment data", "analyzing spectra",
            "Automated analysis of 2D APSY NMR projection", "automated analysis of backbone 1H, 13C and 15N assignments",
            "automated analysis of backbone N, C, H, and backbone dynamics data analysis", "data analysis", "Data analysis", "Data Analysis",
            "Data-Analysis", "DATA ANALYSIS", "CPMG analysis", "CPMG data analysis", "integrated spectral analysis software",
            "integrated spectral analysus software", "N15 T1/T2 data analysis", "NMR analysis", "NMR data analysis", "NMR data assignment",
            "NMR spectral analysis", "NMRVIEW was used to analyze the 3D 13C-editied NOESY, 2D-NOESY, 3D-15N-edited NOESY, and the 3D-13C-filtered NOESY.",
            "PDBanalysis", "PDB analysis", "PDB coordinate analysis", "peak analysis","RDC analysis","rdc data analysis","RDC data analysis",
            "specta analysis", "spectra analysis", "spectra Analysis", "Spectra analysis", "spectral analyses", "spectral analysis", "Spectral analysis",
            "Spectral Analysis", "spectral analysis on papers", "Spectral analysis on Papers", "spectrum analysis", "Spectrum analysis",
            "statistical analysis", "Stereochemical analysis", "structural analysis", "structure analysis", "Structure analysis", "Structure Analysis",
            "structure anaylsis", "visual analysis", "visual analysis of the NMR spectra", "visualization/analysis"
        ],
"chemical shift assignment" : ["Assignment", "ASSIGNMENT", "assignment", "asignment", "assigments", "Assign chemical shifts.", "assignemt",
            "assignments", "Assignments","chemical shift assigment",
            "chemical shift assigment", "chemical shift assignment", "Chemical shift assignment", "chemical shift assignments",
            "Chemical Shift Assignments", "chemical shift autoassignment", "combinatorial chemical shift assignment", "manual assignment",
            "MANUAL ASSIGNMENT", "manual assignment of chamical shifts", "manual assignment of multidimentional NMR spectra", "manual assignments",
            "NMR assignments", "on-screen assignments", "partial sequence specific assignments",
            "Preliminary sequential backbone assignments were obtained using AUTOASSIGN program at Rutgers University with CBCA(CO)NH and HNCACB data",
            "NMRView was used for Assignment", "semi-automated assignment", "semi automated assignments", "semi automated backbone assignment",
            "semi-automated iterative assignment", "semi-automated sequence-specific assignment", "semi-automatic assignment using CACB module",
            "stereospecific assigments", "stereospecific assignmnents", "Strip-based backbone assignment",
            "The majority of assignments were completed by using NMRVIEW", "Used in conjunction with some in-house Tcl scripts for sidechain assignments"
        ],
"peak picking" : ["automated peak picking", "automated peak-picking", "automatic peak picking",
            "Automatic peak pick of frequency-domain 2D and 3D data sets.", "interactive peak-picking", "manual peak picking", "manual peak picking",
            "peak peaking", "peak-pick", "Peak picker", "peak picking", "peak-picking", "Peak picking", "Peak-picking", "Peak Picking",
            "peak picking and visualization of the NMR data", "peak picking for assignments", "peak picking (in-house development)",
            "Peak Picking of 15N edited TOCSY and 15N edited NOESY spectra", "Peak Picking of COSY, NOESY and TOCSY spectra of unlabelled samples",
            "peak picking: PIPP", "peak picking spectra", "peak selection", "primitive interactive peak picker", "Semi-automated Peakpicking",
            "sequence assignments", "sequence specific assignment", "sequence-specific assignment", "sequential and sequence specific assignment",
            "Sequential Assigment", "sequential assignment", "Sequential assignment", "sequential assignments", "sequential backbone assignment",
            "Sidechain assignment with NOESY spectra", "specifically peak-picking", "used for peakpicking all data", "assignments were done by hand"
        ],
"structure solution" : ["initial structure solution", "NMR structure calculation", "NMR structure calculations", "solution structure calculation",
            "structure calcuation", "structure calculation", "Structure calculation", "Structure Calculation", "STRUCTURE CALCULATION",
            "structure calculations", "Structure calculations", "Structure calculation via molecular dynamic simulations",
            "Structure calculation via Monte Carlo calculations", "structure calulation", "structure determination", "Structure determination",
            "structure generation", "structures calculations", "structure solution", "structure Solution", "Structure solution", "STRUCTURE SOLUTION",
            "structure solution calculation", "structure solution(Monomer)", "structure solving", "Strucutre determination",
            "three-dimensional structure calculation"
        ],
"refinement" : ["reffnement in explicit water", "refinemen", "refinement", "refinement\"", "Refinement", "REFINEMENT",
            "refinement and validation", "refinement (cartesian MD in explicit solvent)", "refinement with the Chem.Shift.Module", "refinenment",
            "structure refinement", "Structure refinement", "structure water refinement", "water refinement", "Water refinement"
        ],
"geometry optimization" : null
}
